### ISSUE TITLE
如何能让Dialog内容忽略键盘高度变化？

### ISSUE THREAD

**Issue by lic2050** [TheMelody/AnyPopDialog-Compose#2]
现在这个当键盘弹出时，内容会自动往上移动，如何做可以让内容不随键盘弹出而往上移动？
试过dialogWindow.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING)不行

**Comment by TheMelody** [comment]
> 现在这个当键盘弹出时，内容会自动往上移动，如何做可以让内容不随键盘弹出而往上移动？ 试过dialogWindow.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING)不行

你写的什么示例场景要这样处理？

**Comment by lic2050** [comment]
用弹窗实现类似微信朋友圈评论的消息输入框，当从键盘切换到表情面板时页面会抖动，所以我希望dialog能不受键盘高度影响，然后自己获取键盘高度来实现键盘与表情面板的平滑切换

**Comment by TheMelody** [comment]
> 用弹窗实现类似微信朋友圈评论的消息输入框，当从键盘切换到表情面板时页面会抖动，所以我希望dialog能不受键盘高度影响，然后自己获取键盘高度来实现键盘与表情面板的平滑切换

你在manifest.xml配置你的Activity的windowsoftinputmode为adjustnothing

**Comment by lic2050** [comment]
不行，刚发现DialogProperties的decorFitsSystemWindows = true时，dialog可以不受键盘高度影响，但是content无法延伸到状态栏和导航栏下面，false时content可以延伸到状态栏和导航栏下面，但是又会被键盘高度影响

**Comment by TheMelody** [comment]
> 不行，刚发现DialogProperties的decorFitsSystemWindows = true时，dialog可以不受键盘高度影响，但是content无法延伸到状态栏和导航栏下面，false时content可以延伸到状态栏和导航栏下面，但是又会被键盘高度影响

具体是什么效果，最终要达到什么效果，录个视频看看
