### ISSUE TITLE
在android11的手机上，背景为纯黑色

### ISSUE THREAD

**Issue by vistar1986** [TheMelody/AnyPopDialog-Compose#3]
![screenshot1703230985619](https://github.com/TheMelody/AnyPopDialog-Compose/assets/11677770/78700d31-e7b6-405f-8496-e4e11ef9b2a8)
使用Demo也会出现黑色背景
![screenshot1703231032034](https://github.com/TheMelody/AnyPopDialog-Compose/assets/11677770/9f5fbaa1-c859-464c-b531-2aa1940dd11d)
![screenshot1703231037611](https://github.com/TheMelody/AnyPopDialog-Compose/assets/11677770/926a5f78-d3cd-49f7-922e-a2cbd2bda113)

**Comment by TheMelody** [comment]
不好意思，迟来的回复，最近手里上面其他事情比较多，已经修改好了，周一之前发布新版本哦
