### ISSUE TITLE
位于底部的情况下不适合默认附带systemBarsPadding间距，希望去除默认值

### ISSUE THREAD

**Issue by cy745** [TheMelody/AnyPopDialog-Compose#5]
针对状态栏的高度比较高且需要放在底部的情况，默认边距就显得十分的宽，需要能自定义padding，但是默认写死了systemBarsPadding在AnyPopDialog内部导致这个padding无法调节

| ![S40126-00591431_com lalilu lmusic debug](https://github.com/TheMelody/AnyPopDialog-Compose/assets/35896157/77a4fd26-e812-4098-9ba9-cc63faa39023) | ![S40126-00590845_com lalilu lmusic debug](https://github.com/TheMelody/AnyPopDialog-Compose/assets/35896157/c9914e30-6e5f-4b9a-a5e0-ae32a36897db) |
| --- | --- |

**Comment by TheMelody** [comment]
> 针对状态栏的高度比较高且需要放在底部的情况，默认边距就显得十分的宽，需要能自定义padding，但是默认写死了systemBarsPadding在AnyPopDialog内部导致这个padding无法调节
> 
> | ![S40126-00591431_com lalilu lmusic debug](https://github.com/TheMelody/AnyPopDialog-Compose/assets/35896157/77a4fd26-e812-4098-9ba9-cc63faa39023) | ![S40126-00590845_com lalilu lmusic debug](https://github.com/TheMelody/AnyPopDialog-Compose/assets/35896157/c9914e30-6e5f-4b9a-a5e0-ae32a36897db) |
> | --- | --- |
> 
> 
> 
> 

好的好的，我过两天更新一下配置
