### ISSUE TITLE
不能像Compose自身的Dialog一样预览

### ISSUE THREAD

**Issue by bwmgd** [TheMelody/AnyPopDialog-Compose#8]
如题, AnyPopDialog预览只会显示灰色背景, 只能单独将内容拎出来预览

**Comment by TheMelody** [comment]
> 如题, AnyPopDialog预览只会显示灰色背景, 只能单独将内容拎出来预览

要预览干啥😳，直接run

**Comment by TheMelody** [comment]
1.0.4加了
